name: 'Write Tag to Version File'
author: 'Brett Dorrans'
description: 'A GitHub Action that fetches the latest release tag within a repo and writes this to a file'
inputs:
  filename:
    description: 'The filename to write the version tag to'
    required: true
  placeholder:
    description: 'The placeholder to replace with latest git tag'
    required: false
    default: '${VERSION}'
  tag:
    description: 'The release tag to replace the placeholder'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.filename }}
    - ${{ inputs.placeholder }}
    - ${{ inputs.tag }}
branding:
  icon: 'hash'
  color: 'orange'
